{{- if .Values.gatewayApi.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "linux-mcp-server.fullname" . }}
  labels:
    {{- include "linux-mcp-server.labels" . | nindent 4 }}
  {{- with .Values.gatewayApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- range .Values.gatewayApi.parentRefs }}
    - name: {{ .name | quote }}
      namespace: {{ .namespace | default $.Release.Namespace | quote }}
      {{- with .sectionName }}
      sectionName: {{ . | quote }}
      {{- end }}
    {{- end }}
  {{- if gt (len .Values.gatewayApi.hostnames) 0 }}
  hostnames:
    {{- range .Values.gatewayApi.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gatewayApi.rules }}
    - matches:
        {{- toYaml .matches | nindent 8 }}
      {{- if $.Values.gatewayApi.filters }}
      filters:
        {{- toYaml $.Values.gatewayApi.filters | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "linux-mcp-server.fullname" $ }}
          port: {{ $.Values.service.port }}
          weight: 1
    {{- end }}
{{- end }}
